spring.application.name=remote-classroom

spring.datasource.url=jdbc:mysql://localhost:3306/remote_classroom
spring.datasource.username=root
spring.datasource.password=Shrinithi@1903

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080